version: 2

jobs:
  build-linux-clang:
    docker:
      - image: "debian:buster"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing CLANG
          command: 'apt-get update && apt-get install -y clang'
      - run:
          name: Installing GLEW
          command: 'apt-get update && apt-get install -y libglew-dev'
      - run:
          name: Installing GLM
          command: 'apt-get update && apt-get install -y libglm-dev'
      - run:
          name: Install CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Installing SDL2
          command: 'apt-get update && apt-get install -y libsdl2-dev'
      - run:
          name: Creating Build Directory
          command: 'mkdir -p build'
      - run:
          name: Configuring
          command: 'cd build && cmake ..'
      - run:
          name: Building
          command: 'cd build && make'
  build-linux-gcc:
    docker:
      - image: "debian:buster"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Installing GLEW
          command: 'apt-get update && apt-get install -y libglew-dev'
      - run:
          name: Installing GLM
          command: 'apt-get update && apt-get install -y libglm-dev'
      - run:
          name: Install CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Installing SDL2
          command: 'apt-get update && apt-get install -y libsdl2-dev'
      - run:
          name: Creating Build Directory
          command: 'mkdir -p build'
      - run:
          name: Configuring
          command: 'cd build && cmake ..'
      - run:
          name: Building
          command: 'cd build && make'

workflows:
  version: 2
  build:
     jobs:
       - build-linux-clang
       - build-linux-gcc